### ISSUE TITLE
The Hunt is On - No Aura

### ISSUE THREAD

**Issue by MrSolg** [talamortis/Wildhammerbug#19]
**Description**: Targets for "[The Hunt is On](http://www.wowhead.com/quest=11794/the-hunt-is-on)" do not give off the shadowy aura as expected.

**Current behaviour**: During the [Oculus of the Exorcist](http://www.wowhead.com/item=35125), the targets merely have the dialogue in place to start the fight about them being in the Cult of the Damned.

**Expected behaviour**: Targets needed for the quest should **both** give off a shadowy aura and give dialogue options.

**Steps to reproduce the problem**:

1. Complete the questline up until "The Hunt is On"
2. Activate Oculus of the Damned near any target
3. Check for dialogue and aura.

**QuestID**
11794
**CreatureID**
25827
25828
25248
**Faction**: Alliance

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
Fixed.
