### ISSUE TITLE
Can't learn one handed sword skill as Undead Paladin. Maybe other paladin races too?

### ISSUE THREAD

**Issue by kattanrk** [talamortis/Wildhammerbug#2]
**Description**:
Can't learn one handed sword skill as Undead Paladin
**Current behaviour**: Tell us what happens
Weapon masters in Undercity and Silvermoon teach Undead Paladins 2 Handed Sword skill only. One handed sword skill is not on the menu
**Expected behaviour**: Tell us what should happen instead
We should be able to learn 1 handed sword
**Steps to reproduce the problem**:

1. Be undead paladin
2. Talk to Undercity or Silvermoon weapon master
3. Only see two handed sword skill. No one handed sword skill

**QuestID**

**CreatureID**

**Faction** Horde/Alliance
Unsure. Only played Undead Paladin.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Sylwevrin** [comment]
Issue appears to be that Undead don't start with the sword skill, they start with maces. Same goes for Troll, Orc and Tauren. Blood elves start with swords though.

**Comment by talamortis** [comment]
I will make it so all paladins will learn swords upon creation

**Comment by Ladrek1989** [comment]
INSERT INTO `playercreateinfo_spell` (`racemask`, `classmask`, `spell`,`note`) VALUES
(0, 2, 201,'One-Handed Swords'),

**Comment by Ladrek1989** [comment]
looking into this i will post back shortly

**Comment by smrda** [comment]
Undead paladin here also, same issue, can't learn one handed sword skill anywhere.

**Comment by talamortis** [comment]
paladins should now learn 1h swords on character creation
