### ISSUE TITLE
Southsea Freebooters

### ISSUE THREAD

**Issue by Sylwevrin** [talamortis/Wildhammerbug#3]
Description:
Upon being aggroed, the Southsea Freebooters will not run towards you

Current behaviour: Tell us what happens
They will stay at the spot they were in when they got aggroed, in some cases maintaining a set distance from their target.

Expected behaviour: Tell us what should happen instead
They should run to melee range, or use a ranged weapon.

Steps to reproduce the problem:
Attack one.

CreatureID
7856

Faction Horde/Alliance
Both

**Comment by smrda** [comment]
Also experienced this problem.
