### ISSUE TITLE
Gravis Slipknot

### ISSUE THREAD

**Issue by smrda** [talamortis/Wildhammerbug#4]
**Description**:
This is a rare mob found in Alterac Mountains.

**Current behaviour**: Tell us what happens
He has a wrong display ID and this is what he currently looks like: http://i.imgur.com/4ES7URQ.jpg

**Expected behaviour**: Tell us what should happen instead
He should look like your typical Syndicate mob.

**CreatureID**
14221

**Faction** Horde/Alliance
Both

**Comment by talamortis** [comment]
Fixed on next patch
